### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by alifhakim** [toddhodes/AnimationThrowdown#2]
![image](https://user-images.githubusercontent.com/77255901/175798830-4e21bd4d-c9af-4d06-aff9-5dae8f5402cb.png)

can you tell mw hat is wrong with this. Already try and got this error. It is possible my credential incorrect?

**Comment by toddhodes** [comment]
i don't have a PC to try it on, unfortunately, just mac and linux...

but that tee command is attempting to write a file to the current dir, maybe you don't have write access to that dir?

**Comment by toddhodes** [comment]
also, that "is a directory" indicates your .at_creds isn't a file

run
```
grep user_id ~/.at_creds
```
and make sure that works...

**Comment by alifhakim** [comment]
its working fine now, I accidently save .at_creds as txt. Thanks for the support

**Comment by toddhodes** [comment]
great! let me know if you have any other issues.  and glad to heat PC bash works fine with it.
